### ISSUE TITLE
Drop support for 5.3

### ISSUE THREAD

**Issue by Potherca** [PHPCSStandards/composer-installer#145]
Based on the usage statistics from Packagist and supported versions from PHP_CS we no longer need to support 5.3.

Support can be dropped before we label a stable 1.0 version

**Comment by jrfnl** [comment]
I'm all for it. 👍🏻 

PHPCS 3.x has been out for over four years now (May 2017) and dropped support for PHP 5.3 as well, so I would think most external standards will be using PHPCS 3.x by now and for those who still use PHPCS 2.x, PHP 5.4 would be the new minimum for the plugin and is fully supported on PHPCS 2.x.

It will also simplify a number of things for getting the tests up and running.

The PHP usage stats for this plugin can be found here: https://packagist.org/packages/dealerdirect/phpcodesniffer-composer-installer/php-stats

And this is the status per today:
![image](https://user-images.githubusercontent.com/663378/150995339-57c30de1-1bfe-45fd-bc80-b879d17744ba.png)

The PHPCS version usage stats can be seen here: https://packagist.org/packages/squizlabs/php_codesniffer/stats

With this showing that PHPCS 2.x usage is down to ~2% if all PHPCS installs over the last year or so:
![image](https://user-images.githubusercontent.com/663378/150996166-4981ac24-129e-4a42-a1b1-40a2542dd626.png)
