### ISSUE TITLE
CI: exclude Windows / Composer v1 / PHP 5.5 from builds

### ISSUE THREAD

**Issue by jrfnl** [PHPCSStandards/composer-installer#181]
The Windows / Composer v1 / PHP 5.5 build keeps failing CI runs semi-randomly, causing more and more exceptions for that particular combi to be added to the test suite.

I'm tempted to remove it from the CI for the following reasons:
1. I suspect that that combination will be rare in real life anyway as most users of PHP 5.5 will have upgraded to Composer 2.2.x by now.
2. The principle is still being tested on all the other OS/Composer combinations with PHP 5.5 and should safeguard things well enough.
3. The functionality of the plugin isn't actually failing on this combi, it's just that Composer is not writing the expected messages to the CLI, even though the plugin does do its job.

Opinions ?

**Comment by Potherca** [comment]
Thanks for the ping! This had somehow fallen of my radar. :disappointed_relieved: 

> I'm tempted to remove it from the CI for the following reasons

I concur, remove at will. :+1:
