### ISSUE TITLE
Project directory no longer scanned

### ISSUE THREAD

**Issue by Empornium** [PHPCSStandards/composer-installer#202]
## Problem/Motivation

README states that:
```Matching packages and the project itself are scanned for PHP_CodeSniffer rulesets.```

It appears this has now been limited to working only if the current project is itself a coding standard (phpcodesniffer-standard), some projects have defined their own custom coding standard and rely on this package to install them for phpcs to use.

Suspected commit that introduced this breaking change:
https://github.com/PHPCSStandards/composer-installer/commit/2de5e4b4906a28cf854da24ae725357eb832c318

## Expected behaviour

Custom coding standards should be detected and installed regardless of the parent project type.

**Comment by jrfnl** [comment]
@Empornium I'm not sure I understand the problem.

> some projects have defined their own custom coding standard and rely on this package to install them for phpcs to use.

A project can still define their own custom coding standard in a `[.]phpcs.xml[.dist]` file. Custom standards do not need to be registered with PHPCS. Only named standards, which add new sniffs, needs to be registered with PHPCS.

**Comment by jrfnl** [comment]
Closing for lack of reply. If this is still an issue, please add extra information to make this actionable and then the issue can be re-opened.
