### ISSUE TITLE
Add PHPUnit tests and CI

### ISSUE THREAD

**Issue by frenck** [PHPCSStandards/composer-installer#9]
## Motivation

The user base of this plugin seems to grow, which is awesome but we need to maintain its quality, while also being able to accept PR's.

## Proposed changes

PHPUnit tests for this plugin and Travis CI running them on every single commit and/or PR.

1. [ ] Create PHPUnit tests.
1. [x] Configure [Travis CI with this repository](https://travis-ci.org/DealerDirect/phpcodesniffer-composer-installer) (resolved by #27).
1. [x] Force repository setting to require successful builds on PR's.

**Comment by Potherca** [comment]
I'll pick up writing unit tests.

**Comment by christopher-hopper** [comment]
I can assist with the Travis CI integration. I have recent experience on this using Appveyor (Windows) and CircleCI. Agree that Travis is the best option for this project.

**Comment by frenck** [comment]
@christopher-hopper Thank you for your offer.

I think it would be wise for us to first setup the basics with our Travis CI account ourselves, afterwards your are of course welcome to improve 🥇

**Comment by frenck** [comment]
Related to this issue:

I've added Scrutinizer to this repository.

**Comment by Potherca** [comment]
Travis and PR-build have been resolved.

**Comment by jrfnl** [comment]
Just wondering: Should these tests be run in combination with various PHPCS versions ?

**Comment by Potherca** [comment]
I've got time to look into this in the coming weeks. Will report progress when I make it. 👍
